# Version 3 syntax :
# https://docs.docker.com/compose/compose-file/#/versioning
version: '3'
networks:
    front_end:
        driver: bridge
    back_end:
        driver: bridge
services:
##########################
# Setup tomcat container
##########################
    tomcat:
        container_name: Projet_tomcat
        restart: always
        image: tomcat:9.0.14-jre8-alpine
        ports:
            - 80:80
        networks:
            - front_end
            - back_end
        volumes:
            - ./projet-jee.war:/var/lib/tomcat9/webapps
##########################
# Setup MySQL master container
##########################
    mysqlmaster:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - back_end
        volumes:
            - ./data/mysql-master:/var/lib/mysql/
            - ./config/mysql-master:/etc/mysql/conf.d/
##########################
# Setup MySQL slave container
##########################
    mysqlslave:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - back_end
        volumes:
            - ./data/mysql-slave:/var/lib/mysql/
            - ./config/mysql-slave:/etc/mysql/conf.d/
##########################
# Setup MySQL configure container
##########################
    mysqlconfigure:
        image: mysql:5.7
        depends_on:
            - mysqlmaster
            - mysqlslave
        environment:
            - MYSQL_SLAVE_PASSWORD=root
            - MYSQL_MASTER_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_REPLICATION_USER=repl
            - MYSQL_REPLICATION_PASSWORD=repl
        networks:
            - back_end
        volumes:
            - ./config/mysql_connector.sh:/tmp/mysql_connector.sh
            - ./config/create.sql:/tmp/create.sql
        command: /bin/bash -x /tmp/mysql_connector.sh

