CREATE DATABASE IF NOT EXISTS jee;
CREATE USER IF NOT EXISTS 'jee'@'%' IDENTIFIED BY 'projetjee';
GRANT USAGE ON *.* TO  'jee'@'%' IDENTIFIED BY  'projetjee' WITH GRANT OPTION;
GRANT SELECT , INSERT , UPDATE , CREATE , ALTER , DELETE , DROP ON  `jee`.* TO  'jee'@'%';
FLUSH PRIVILEGES;